FROM confluentinc/cp-schema-registry:latest

USER root

WORKDIR /app

RUN dnf install -y jq

COPY ./bash_scripts/init.sh /app/bash_scripts/init.sh
COPY ./schemas /app/schemas  

RUN chmod +x /app/bash_scripts/init.sh

ENTRYPOINT bash -c "/app/bash_scripts/init.sh && exec /bin/bash"

