FROM cassandra:latest

Workdir /app

copy ./bash_scripts /app/bash_scripts
copy ./cql_scripts /app/cql_scripts

RUN chmod +x /app/bash_scripts/init.sh

ENTRYPOINT bash -f "/app/bash_scripts/init.sh"