# Utiliser une image officielle de Python comme base
FROM openjdk:11

# Installer Python et pip
RUN apt-get update && apt-get install -y python3 python3-pip

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip3 install --no-cache-dir -r requirements.txt 

EXPOSE 8888

# Définir le répertoire de travail
WORKDIR /app

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
