FROM confluentinc/cp-kafka:latest

USER root

WORKDIR /app

COPY ./bash_scripts/aliases.sh /app/aliases.sh
COPY ./bash_scripts/init.sh /app/init.sh

RUN chmod +x /app/init.sh 
Run bash /app/aliases.sh

ENTRYPOINT bash -c "/app/init.sh && exec /bin/bash"
